--- 
- name: Build worker AMI
  hosts: all
  become: true

  vars:
    some: value

  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }} {{ ansible_distribution_release }} {{ ansible_distribution_version }}"
  
  - name: Install packages
    apt:
      pkg:
      - curl
      - ca-certificates
      - apt-transport-https
      - python3-pip
      state: latest
      update_cache: true
      cache_valid_time: 10
  
  - name: Create app directory
    file:
      path: /var/lib/sample-app
      state: directory
  
  - name: Copy app
    copy:
      src: ./app
      dest: /var/lib/sample-app/
      directory_mode: yes
